---
title: "Network treatment ranking"
author: "dECMT"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(ggplot2)
require(dplyr)
require(tidyr)
require(gridExtra)
require(patchwork)
```

## Objective

* Define a function that accepts a set of variants and a set of treatments (i.e. one or more drugs) and ranks the treatments based on the proportion of variant changes the treatments oppose.  
  
```{r download drug and variant effects}
## effects of variants and drugs on downstream cancer drivers have been precomputed by separate script
## results were saved to csv and have been uploaded to public github repo... 
drug_effects_url <- "https://raw.githubusercontent.com/digital-ECMT/network_data/main/drug_effects.csv"
drug_effects <- read.csv(drug_effects_url, stringsAsFactors = FALSE)


variant_effects_url <- "https://raw.githubusercontent.com/digital-ECMT/network_data/main/variant_effects.csv"
variant_effects <- read.csv(variant_effects_url, stringsAsFactors = FALSE)

## customise labels for roles
variant_effects$affected_gene_role <- factor(x=variant_effects$affected_gene_role, levels = c("ONCOGENE", "TUMOUR SUPPRESSOR"), labels = c("ONCOGENES", "TUMOUR SUPPRESSORS"))

drug_effects$affected_gene_role <- factor(x=drug_effects$affected_gene_role, levels = c("ONCOGENE", "TUMOUR SUPPRESSOR"), labels = c("ONCOGENES", "TUMOUR SUPPRESSORS"))

```



```{r download drug dictionary}
drug_dictionary_url <- "https://raw.githubusercontent.com/digital-ECMT/network_data/main/NCI_drug_dictionary.csv"
drug_dictionary <- read.csv(drug_dictionary_url, stringsAsFactors = FALSE)
```


```{r define some example NCIt codes and variants}

example_gene_variants <- c("KRAS GoF", "ARID1A LoF", "PIK3CA GoF", "BRAF GoF")





example_patient_table <- data.frame(groupvar = "patient X", 
                                    groupmembers = c(example_gene_variants))

example_variant_list = list(c("KRAS GoF", "ARID1A LoF", "PIK3CA GoF", "BRAF GoF"))

example_treatments_table <- data.frame(groupvar = character(0), NCIt_code = character(0)) %>%
    add_row(groupvar = "VS-6766 monotherapy", NCIt_code = c("C80060")) %>%
    add_row(groupvar = "VS-6766 plus Everolimus", NCIt_code = c("C80060", "C48387")) %>%
    add_row(groupvar = "Ipatasertib plus Atezolizumab", NCIt_code = c("C91072", "C106250")) %>%
    add_row(groupvar = "VS-6766 pus Defactinib", NCIt_code = c("C80060", "C79809")) %>%
    add_row(groupvar = "CPI-0209", NCIt_code = c("C167347")) %>%
    nest(groupmembers=NCIt_code)



example_treatment_list <- list("VS-6766"  = c("C80060"), "VS-6766 + Everolimus" = c("C80060", "C48387"), "Ipatasertib + Atezolizumab" = c("C91072", "C106250"), "VS-6766 + Defactinib" = c("C80060", "C79809"), "Tulmimetostat" = c("C167347"))

# example_treatments_table <- data.frame(groupvar = c("VS-6766 monotherapy", "VS-6766 plus Everolimus", "Ipatasertib plus Atezolizumab", "VS-6766 pus Defactinib", "CPI-0209"), 
#                                        groupmembers = c("C1872", "C154287", "C157493", "C1872", "C157493"))


# example_NCIt_codes <- c("C71146", "C2411", "C1872", "C157493")
# 
# example_treatments_table <- data.frame(groupvar = c("Midostaurin", "Sotorasib", "Adagrasib", "Midostaurin + Adagrasib", "Midostaurin + Adagrasib"), 
#                                        groupmembers = c("C1872", "C154287", "C157493", "C1872", "C157493"))
```

```{r define function to calculate net effect of variants, fig.width=24, fig.height=8, message=FALSE}

calculate_netVariantFx <- function(variantList, maxDepth=2) {
  variantPlot <- variant_effects %>%
    dplyr::filter(source_node %in% variantList[[1]]) %>%
    dplyr::filter(pathlength <= maxDepth) %>%
    # dplyr::filter(affected_gene == "PIK3CA") %>%
    as.data.frame() %>%
    ggplot(aes(x=affected_gene, y=source_node, fill = link_product/pathlength)) +
    geom_tile(color = "black") +
      scale_fill_gradient2(midpoint = 0, low = "blue", mid = "white",
                           high = "red", space = "Lab", name = "Effect on tumour driver gene", limits = c(-1,1), breaks = c(1,0.5, 0,-0.5, -1), labels = c("Direct activation", "Indirect activation", "No effect", "Indirect inactivation", "Direct inactivation") ) +
      labs(title = paste0("Effect of patient variants on known tumour drivers (max depth:", maxDepth, ")"), x="Driver genes", y="Condition") +
      scale_x_discrete(position = "top") +
      facet_grid(source_node_type ~ affected_gene_role, scales = "free", space = "free") 
  
  variantTable <- variant_effects %>%
    dplyr::filter(source_node %in% variantList[[1]]) %>%
    dplyr::filter(pathlength <= maxDepth) %>%
    group_by(affected_gene) %>%
    summarise(
        net_effect = sum(link_product)
    ) %>%
    as.data.frame()
  
  print(variantPlot)
  return(variantTable)
  
}

## example
netVariants <- calculate_netVariantFx(variantList = example_variant_list)
```

```{r define function to calculate net effect of treatments, fig.width=24, fig.height=8, message=FALSE}

calculate_netTreatmentFx <- function(treatmentList, maxDepth=2) {
  # create an empty table that will hold treatment effects
  treatment_effects <- drug_effects[0, ] %>%
    mutate("treatment"=character(0))
  
  for(i in 1:length(treatmentList)) {
    #print(treatmentList[[i]])
    temp <- drug_effects %>%
      dplyr::filter(pathlength <= maxDepth) %>%
      dplyr::filter(source_node %in% treatmentList[[i]]) %>%
      #dplyr::filter(affected_gene %in% netVariants$affected_gene) %>%
      mutate("treatment"=names(treatmentList)[i]) 
    
    ## bind onto treatment_effects table
    treatment_effects <- rbind(treatment_effects, temp)
    }
  
  # create plot
  treatmentPlot <- treatment_effects %>%
      ggplot(aes(x=affected_gene, y=source_node, fill = link_product/pathlength)) +
      geom_tile(color = "black") +
        scale_fill_gradient2(midpoint = 0, low = "blue", mid = "white",
                             high = "red", space = "Lab", name = "Effect on tumour driver gene", limits = c(-1,1), breaks = c(1,0.5, 0,-0.5, -1), labels = c("Direct activation", "Indirect activation", "No effect", "Indirect inactivation", "Direct inactivation") ) +
        labs(title = paste0("Effect of selected treatments on known tumour drivers (max depth:", maxDepth, ")"), x="Driver genes", y="Drug") +
        scale_x_discrete(position = "top") +
        facet_grid(treatment ~ affected_gene_role, scales = "free", space = "free", switch = "y") +
        scale_y_discrete(position = "right") +
        theme(strip.text.y.left = element_text(angle = 0))

  # summarise net effect 
  treatmentTable <- treatment_effects %>%
    group_by(treatment, affected_gene) %>%
    summarise(
        net_effect = sum(link_product)
    ) %>%
    as.data.frame()  
  
  
  print(treatmentPlot)
  return(treatmentTable)
}

## example
netTreatments <- calculate_netTreatmentFx(treatmentList = example_treatment_list)


```





```{r define treatment ranking function}


rankTreatments <- function(variantList, maxDepth=2, treatmentList, allgenes = FALSE) {
  variantTable <- variant_effects %>%
    dplyr::filter(source_node %in% variantList[[1]]) %>%
    dplyr::filter(pathlength <= maxDepth) %>%
    mutate("treatment"="none") %>%
    group_by(treatment, affected_gene) %>%
    summarise(
        net_effect = sum(link_product)
    ) %>%
    as.data.frame()
  
  # create an empty table that will hold treatment effects
  treatment_effects <- drug_effects[0, ] %>%
    mutate("treatment"=character(0))
  
  for(i in 1:length(treatmentList)) {
    #print(treatmentList[[i]])
    temp <- drug_effects %>%
      dplyr::filter(pathlength <= maxDepth) %>%
      dplyr::filter(source_node %in% treatmentList[[i]]) %>%
      #dplyr::filter(affected_gene %in% netVariants$affected_gene) %>%
      mutate("treatment"=names(treatmentList)[i]) 
    
    ## bind onto treatment_effects table
    treatment_effects <- rbind(treatment_effects, temp)
  }
  
  # summarise net effect 
  treatment_effects <- treatment_effects %>%
    group_by(treatment, affected_gene) %>%
    summarise(
        net_effect = sum(link_product)
    ) %>%
    as.data.frame()
  
  
  ## if allgenes = FALSE, ignore genes affected by treatment but not by variants... 
  if(allgenes == FALSE) {
    treatment_effects <- dplyr::filter(treatment_effects, affected_gene %in% variantTable$affected_gene)}
  
  ## row bind variant and treatment effects and calculate distances
  treatment_effects %>%
    rbind(variantTable) %>%
    mutate(treatment = {relevel(factor(.$treatment), ref="none")}) %>%
    reshape2::acast(treatment ~ affected_gene, value.var = "net_effect") %>%
    replace(is.na(.), 0) %>%
    dist(method = "manhattan")
  
  
  
  
  # ## row bind variant and treatment effects and calculate distances
  # rbind(variantTable, treatment_effects) %>%
  #   mutate(treatment = {relevel(factor(.$treatment), ref="none")}) %>%
  #   reshape2::acast(treatment ~ affected_gene, value.var = "net_effect") %>%
  #   replace(is.na(.), 0) %>%
  #   dist(method = "manhattan")

}


```



  